export const ACHIEVEMENTS = {
  FIRST_SESSION: {
    id: 'first-session',
    name: 'First Session',
    description: 'Complete your first study session',
    icon: 'Flame',
    category: 'milestone',
    rarity: 'common',
  },
  PERFECT_SCORE: {
    id: 'perfect-score',
    name: 'Perfect Focus',
    description: 'Finish a session with 100 focus score',
    icon: 'Target',
    category: 'performance',
    rarity: 'rare',
  },
  THREE_DAY_STREAK: {
    id: 'three-day-streak',
    name: '3-Day Streak',
    description: 'Maintain a 3-day focus streak',
    icon: 'Zap',
    category: 'streak',
    rarity: 'uncommon',
  },
  SEVEN_DAY_STREAK: {
    id: 'seven-day-streak',
    name: '7-Day Streak',
    description: 'Achieve a 7-day consecutive focus streak',
    icon: 'Crown',
    category: 'streak',
    rarity: 'uncommon',
  },
  SPEED_RETURNER: {
    id: 'speed-returner',
    name: 'Speed Returner',
    description: 'Return to focus within 5 seconds, 3 times in one session',
    icon: 'Zap',
    category: 'performance',
    rarity: 'uncommon',
  },
  NIGHT_OWL: {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Complete a study session after 10 PM',
    icon: 'Moon',
    category: 'special',
    rarity: 'common',
  },
  EARLY_BIRD: {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete a study session before 7 AM',
    icon: 'Sun',
    category: 'special',
    rarity: 'common',
  },
  DEBT_CLEARED: {
    id: 'debt-cleared',
    name: 'Debt Cleared',
    description: 'Complete a strict focus debt clearing session',
    icon: 'CheckCircle',
    category: 'performance',
    rarity: 'uncommon',
  },
  ACCOUNTABLE: {
    id: 'accountable',
    name: 'Accountable',
    description: 'Send an accountability email from session summary',
    icon: 'Send',
    category: 'special',
    rarity: 'uncommon',
  },
  STREAK_SAVER: {
    id: 'streak-saver',
    name: 'Streak Saver',
    description: 'Complete a session on the last day before streak reset',
    icon: 'Shield',
    category: 'streak',
    rarity: 'rare',
  },
  COMEBACK_KING: {
    id: 'comeback-king',
    name: 'Comeback King',
    description: 'Restart after 0-day streak and reach 7 days again',
    icon: 'TrendingUp',
    category: 'milestone',
    rarity: 'epic',
  },
};

export const ACHIEVEMENT_LIST = Object.values(ACHIEVEMENTS);
